export const DEFAULT_SETTINGS = {
  CLAUDE_MEM_MODEL: 'claude-sonnet-5',
  CLAUDE_MEM_CONTEXT_OBSERVATIONS: '50',
  CLAUDE_MEM_WORKER_PORT: '37700',
  CLAUDE_MEM_WORKER_HOST: '127.0.0.1',

  CLAUDE_MEM_PROVIDER: 'claude',
  CLAUDE_MEM_GEMINI_API_KEY: '',
  CLAUDE_MEM_GEMINI_MODEL: 'gemini-flash-latest',
  CLAUDE_MEM_OPENROUTER_API_KEY: '',
  CLAUDE_MEM_OPENROUTER_MODEL: 'xiaomi/mimo-v2-flash:free',
  CLAUDE_MEM_OPENROUTER_SITE_URL: '',
  CLAUDE_MEM_OPENROUTER_APP_NAME: 'claude-mem',
  CLAUDE_MEM_CODEX_MODEL: 'gpt-5.6-luna',
  CLAUDE_MEM_CODEX_PATH: 'codex',
  CLAUDE_MEM_CODEX_REASONING_EFFORT: 'low',
  CLAUDE_MEM_CODEX_MAX_CONTEXT_MESSAGES: '20',
  CLAUDE_MEM_CODEX_MAX_TOKENS: '100000',
  CLAUDE_MEM_CODEX_TIMEOUT_MS: '120000',
  CLAUDE_MEM_CODEX_MAX_OBSERVATIONS_PER_PROMPT: '6',
  CLAUDE_MEM_GEMINI_RATE_LIMITING_ENABLED: 'true',

  CLAUDE_MEM_CONTEXT_SHOW_READ_TOKENS: 'false',
  CLAUDE_MEM_CONTEXT_SHOW_WORK_TOKENS: 'false',
  CLAUDE_MEM_CONTEXT_SHOW_SAVINGS_AMOUNT: 'false',
  CLAUDE_MEM_CONTEXT_SHOW_SAVINGS_PERCENT: 'true',

  CLAUDE_MEM_CONTEXT_FULL_COUNT: '0',
  CLAUDE_MEM_CONTEXT_FULL_FIELD: 'narrative',
  CLAUDE_MEM_CONTEXT_SESSION_COUNT: '10',

  CLAUDE_MEM_CONTEXT_SHOW_LAST_SUMMARY: 'true',
  CLAUDE_MEM_CONTEXT_SHOW_LAST_MESSAGE: 'false',
} as const;
