import { describe, it, expect, beforeEach, afterEach } from 'bun:test';
import { SessionStore } from '../src/services/sqlite/SessionStore.js';

describe('SessionStore', () => {
  let store: SessionStore;

  beforeEach(() => {
    store = new SessionStore(':memory:');
  });

  afterEach(() => {
    store.close();
  });

  it('should correctly count user prompts', () => {
    const claudeId = 'claude-session-1';
    store.createSDKSession(claudeId, 'test-project', 'initial prompt');
    
    expect(store.getPromptNumberFromUserPrompts(claudeId)).toBe(0);

    store.saveUserPrompt(claudeId, 1, 'First prompt');
    expect(store.getPromptNumberFromUserPrompts(claudeId)).toBe(1);

    store.saveUserPrompt(claudeId, 2, 'Second prompt');
    expect(store.getPromptNumberFromUserPrompts(claudeId)).toBe(2);

    store.createSDKSession('claude-session-2', 'test-project', 'initial prompt');
    store.saveUserPrompt('claude-session-2', 1, 'Other prompt');
    expect(store.getPromptNumberFromUserPrompts(claudeId)).toBe(2);
  });

  it('should store observation with timestamp override', () => {
    const claudeId = 'claude-sess-obs';
    const memoryId = 'memory-sess-obs';
    const sdkId = store.createSDKSession(claudeId, 'test-project', 'initial prompt');

    store.updateMemorySessionId(sdkId, memoryId);

    const obs = {
      type: 'discovery',
      title: 'Test Obs',
      subtitle: null,
      facts: [],
      narrative: 'Testing',
      concepts: [],
      files_read: [],
      files_modified: []
    };

    const pastTimestamp = 1600000000000; 

    const result = store.storeObservation(
      memoryId, // Use memorySessionId for FK reference
      'test-project',
      obs,
      1,
      0,
      pastTimestamp
    );

    expect(result.createdAtEpoch).toBe(pastTimestamp);

    const stored = store.getObservationById(result.id);
    expect(stored).not.toBeNull();
    expect(stored?.created_at_epoch).toBe(pastTimestamp);

    expect(new Date(stored!.created_at).getTime()).toBe(pastTimestamp);
  });

  it('sets session identity (memory_session_id + worker_port) before an observation can be accepted (#2533)', () => {
    const claudeId = 'claude-identity-1';
    const memoryId = 'memory-identity-1';
    const sdkId = store.createSDKSession(claudeId, 'test-project', 'initial prompt');

    // Fresh session has NO identity yet: memory_session_id is NULL and an
    // observation insert would violate the NOT NULL FK — nothing can be stored.
    const before = store.getSessionById(sdkId);
    expect(before?.memory_session_id).toBeNull();

    // Identity registration is the gate that runs before storeObservations.
    store.ensureMemorySessionIdRegistered(sdkId, memoryId, 37742);

    const after = store.getSessionById(sdkId);
    expect(after?.memory_session_id).toBe(memoryId);
    const portRow = store.db.prepare('SELECT worker_port FROM sdk_sessions WHERE id = ?').get(sdkId) as { worker_port: number | null };
    expect(portRow.worker_port).toBe(37742);

    // Only AFTER identity is set can an observation be accepted into the table.
    const result = store.storeObservation(memoryId, 'test-project', {
      type: 'discovery',
      title: 'Identity gate',
      subtitle: null,
      facts: [],
      narrative: 'Stored only after identity was registered',
      concepts: [],
      files_read: [],
      files_modified: []
    }, 1);
    const stored = store.getObservationById(result.id);
    expect(stored?.memory_session_id).toBe(memoryId);
  });

  it('should store summary with timestamp override', () => {
    const claudeId = 'claude-sess-sum';
    const memoryId = 'memory-sess-sum';
    const sdkId = store.createSDKSession(claudeId, 'test-project', 'initial prompt');

    store.updateMemorySessionId(sdkId, memoryId);

    const summary = {
      request: 'Do something',
      investigated: 'Stuff',
      learned: 'Things',
      completed: 'Done',
      next_steps: 'More',
      notes: null
    };

    const pastTimestamp = 1650000000000;

    const result = store.storeSummary(
      memoryId, // Use memorySessionId for FK reference
      'test-project',
      summary,
      1,
      0,
      pastTimestamp
    );

    expect(result.createdAtEpoch).toBe(pastTimestamp);

    const stored = store.getSummaryForSession(memoryId);
    expect(stored).not.toBeNull();
    expect(stored?.created_at_epoch).toBe(pastTimestamp);
  });

  it('stamps the originating content_session_id onto generated observation and summary rows (#2769)', () => {
    const claudeId = 'claude-live-2769';
    const memoryId = 'memory-live-2769';
    const sdkId = store.createSDKSession(claudeId, 'test-project', 'initial prompt');
    store.updateMemorySessionId(sdkId, memoryId);

    const observations = [{
      type: 'discovery',
      title: 'Live observation',
      subtitle: null,
      facts: [],
      narrative: 'Generated by the live observer pipeline',
      concepts: [],
      files_read: [],
      files_modified: []
    }];
    const summary = {
      request: 'Do the thing',
      investigated: 'Looked around',
      learned: 'Found it',
      completed: 'Done',
      next_steps: 'Ship',
      notes: null
    };

    const result = store.storeObservations(
      memoryId,
      'test-project',
      observations,
      summary,
      1,
      0,
      undefined,
      undefined,
      claudeId
    );

    const obsRow = store.db
      .prepare('SELECT content_session_id FROM observations WHERE id = ?')
      .get(result.observationIds[0]) as { content_session_id: string | null };
    expect(obsRow.content_session_id).toBe(claudeId);

    const summaryRow = store.db
      .prepare('SELECT content_session_id FROM session_summaries WHERE id = ?')
      .get(result.summaryId) as { content_session_id: string | null };
    expect(summaryRow.content_session_id).toBe(claudeId);
  });

  it('backfills content_session_id on a re-opened legacy database, idempotently (#2769)', () => {
    const hasColumn = (table: string) =>
      (store.db.query(`PRAGMA table_info(${table})`).all() as Array<{ name: string }>)
        .some(c => c.name === 'content_session_id');
    const hasIndex = (table: string, index: string) =>
      (store.db.query(`PRAGMA index_list(${table})`).all() as Array<{ name: string }>)
        .some(i => i.name === index);

    expect(hasColumn('observations')).toBe(true);
    expect(hasColumn('session_summaries')).toBe(true);

    // Simulate a database created before migration 35.
    store.db.run('DROP INDEX IF EXISTS idx_observations_content_session');
    store.db.run('DROP INDEX IF EXISTS idx_session_summaries_content_session');
    store.db.run('ALTER TABLE observations DROP COLUMN content_session_id');
    store.db.run('ALTER TABLE session_summaries DROP COLUMN content_session_id');
    store.db.prepare('DELETE FROM schema_versions WHERE version = 35').run();
    expect(hasColumn('observations')).toBe(false);

    // Re-opening the store on the same handle re-runs the migration sequence.
    new SessionStore(store.db);

    expect(hasColumn('observations')).toBe(true);
    expect(hasColumn('session_summaries')).toBe(true);
    expect(hasIndex('observations', 'idx_observations_content_session')).toBe(true);
    expect(hasIndex('session_summaries', 'idx_session_summaries_content_session')).toBe(true);
    expect(
      (store.db.prepare('SELECT COUNT(*) AS n FROM schema_versions WHERE version = 35').get() as { n: number }).n
    ).toBe(1);

    // Running it a third time is a no-op, not an error.
    expect(() => new SessionStore(store.db)).not.toThrow();
  });
});
