import { chmodSync, mkdirSync, writeFileSync } from 'fs';
import { join } from 'path';

// Normalize to forward slashes so the path is valid inside a sh script on all
// platforms (matches the rest of the plugin which already requires sh/bash).
function toShPath(p: string): string {
  return p.replace(/\\/g, '/');
}

export function writeMcpLauncher(dataDir: string, knownMcpServerPath: string): void {
  const binDir = join(dataDir, 'bin');
  mkdirSync(binDir, { recursive: true });

  const launcherPath = join(binDir, 'mcp-server.sh');
  const shPath = toShPath(knownMcpServerPath);

  // Tries the known install path first, then falls back to full discovery so it
  // works across Claude Code, Codex, PLUGIN_ROOT env, and dev mode.
  const content = `#!/bin/sh
# Auto-generated by claude-mem installer - do not edit manually
if [ -f "${shPath}" ]; then exec node "${shPath}"; fi
_C="\${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
_E="\${CLAUDE_PLUGIN_ROOT:-\${PLUGIN_ROOT:-}}"
_P=$({
  [ -n "$_E" ] && printf '%s\\n' "$_E"
  ls -dt \\
    "$HOME/.codex/plugins/cache/claude-mem-local/claude-mem"/[0-9]*/ \\
    "$HOME/.codex/plugins/cache/thedotmack/claude-mem"/[0-9]*/ \\
    "$_C/plugins/cache/thedotmack/claude-mem"/[0-9]*/ 2>/dev/null
  printf '%s\\n' "$_C/plugins/marketplaces/thedotmack/plugin"
} | while IFS= read -r _R; do
  [ -d "$_R/plugin/scripts" ] && _Q="$_R/plugin" || _Q="$_R"
  [ -f "$_Q/scripts/mcp-server.cjs" ] && { printf '%s\\n' "$_Q"; break; }
done)
[ -n "$_P" ] || { echo "claude-mem: mcp server not found" >&2; exit 1; }
exec node "$_P/scripts/mcp-server.cjs"
`;

  writeFileSync(launcherPath, content, 'utf-8');
  chmodSync(launcherPath, 0o755);
}
